global:
  scrape_interval: 5s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'localhost:9093'
rule_files:
  - alert.rules.yml
scrape_configs:
  - job_name: blackbox
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module:
        - http_2xx
    file_sd_configs:
      - files:
        - blackbox_targets.yml
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'localhost:9115'
  - job_name: API
    scrape_interval: 10m
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    file_sd_configs:
      - files:
        - app_metrics_targets.json
  - job_name: node_exporter
    file_sd_configs:
      - files:
        - node_exporter_targets.json
